language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t codiemullins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codiemullins/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-687710132501
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
