language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t codiemullins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codiemullins/docker-react npm run test
