language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t codiemullins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codiemullins/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  app: travis-cd
  env: travis-cd-env
  bucket: elasticbeanstalk-us-east-1-687710132501
  bucket_path: travis-cd
  on:
    branch: main
